### ISSUE TITLE
PID_FILE not specified

### ISSUE THREAD

**Issue by ruxkor** [evertramos/docker-wordpress-backup#1]
The `PID_FILE` variable is not set. This causes the ./run-backup.sh to echo directly to the directory and then `rm -f` the directory. Thankfully (!) this does not cause any malfunction, because no `-r` is specified. 

https://github.com/evertramos/docker-wordpress-backup/blob/735bf759194c18d2ea60b80b74dfd5a0e329d9e5/base/pid.sh#L6-L12

**Comment by evertramos** [comment]
Hello @ruxkor!!

Thanks for your comments, sorry for that... I had this in my basic .env file... but you are totally right, it is not in the .env.sample from the [docker wordpress letsencrypt](https://github.com/evertramos/docker-wordpress-letsencrypt/blob/master/.env.sample).

I also fixed some validation on that subject as well.

Once again, thanks for you attention to that.

I have being really busy these days and did not get the chance to finish it all the way I have planned, but I will work on that.

Cheers!
